name: Herald.MessageQueue

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: Build
      run: dotnet build -c Release     

    - name: Test
      env:
        SKIP: true
      run: |
          docker-compose -f .docker/test-enviroment.yml up -d
          echo "sleep 15"
          sleep 15
          dotnet test "--logger:junit;LogFilePath=./test-reports/results.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="coverage.xml" /p:Thereshold=80

    - name: Publish Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: | 
          curl -s https://codecov.io/bash > codecov
          chmod +x codecov
          find . -name "coverage.xml" -print -quit | xargs -i bash -c "cp {} coverage.xml;"
          ./codecov -f "coverage.xml" -t $CODECOV_TOKEN
